variables:
  PRODUCT: innote
  MICROSERVICE_NAME: express_boilerplate
  DOCKER_IMAGE: ${PRODUCT}/express-boilerplate
  BUILD_TYPE: DOCKERCOMPOSE
  DELAY: "11 min"



include:
  - project: 'infrastructure/ci-helm'
    ref: master
    file: 'ci-templates/ci.yml'


.only-default: &only-default
  only:
    - merge_requests
    - master


test:
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:
    - docker pull mongo:3.2
    - docker-compose -f docker-compose.test.yml down
    - docker-compose -f docker-compose.test.yml build
    - docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from express-boilerplate
    - docker cp express-boilerplate:/app/coverage/cobertura-coverage.xml ./cobertura-coverage.xml
    - docker-compose -f docker-compose.test.yml down
  <<: *only-default
  tags:
    - shell
    - ubuntu
  artifacts:
    paths:
      - ./cobertura-coverage.xml
    expire_in: 1 week


linting:
  image: public.ecr.aws/y3c6e3y9/python:3.6-slim-stretch
  stage: linting
  script:
    - pip install black
  allow_failure: true
  tags:
    - docker
  <<: *only-default

