version: "3"
services:
  innote:
    image: '${CI_REGISTRY_ACCOUNT}/${CI_REGISTRY_IMAGE}:${TAG}'
    build:
      context: .
      args:
      - ENV=${ENV:-dev}
      dockerfile: Dockerfile
    entrypoint: /bin/ash -c "./start.sh dev"
    environment:
      - ENV=dev
      - ENV_CODE=dev
