version: "3"
services:
  node-boilerplate:
    container_name: node-boilerplate
    build:
      context: .
      args:
      - ENV=${ENV:-prod}
      dockerfile: Dockerfile
    entrypoint: /bin/ash -c "/app/start.sh prod"
    environment:
      - ENV=prod
      - ENV_CODE=prod
      - MONGO_HOST=mongodb
    depends_on:
      - "mongodb"
    links:
      - mongodb
    ports:
      - 8000:8000

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - ./database/mongodb:/data/db

