version: "3"
services:
  node-boilerplate:
    build:
      context: .
      args:
      - ENV=${ENV:-test}
      dockerfile: Dockerfile
    entrypoint: /bin/ash -c "./start.sh test"
    environment:
      - ENV=test
      - ENV_CODE=test
  