version: "3"
services:
  express-boilerplate:
    container_name: express-boilerplate
    build:
      context: .
      args:
      - ENV=${ENV:-test}
      dockerfile: Dockerfile
    entrypoint: /bin/ash -c "./start.sh test"
    environment:
      - ENV=test
      - ENV_CODE=test
      - MONGO_HOST=mongodb
    depends_on:
      - "mongodb"
    links:
      - mongodb
    ports:
      - 8000:8000

  mongodb:
    image: mongo
    container_name: mongodb
    logging:
      driver: "none"
    command: mongod --quiet --logpath /dev/null 

